ERROR 2022-08-15 17:32:44,300 - Error Message from get_list_item
Traceback (most recent call last):
  File "c:\Users\SVD_INTEL_NUC\Desktop\TerryFolder\project_intel_smoke_test\SMI_OneTouch_20220816A.py", line 1033, in mainWork
    self.passSig.emit("None", scriptname)
UnboundLocalError: local variable 'scriptname' referenced before assignment
