ERROR 2022-07-25 11:20:46,888 - Error Message from Class of getSHA
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\project_intel_smoke_test\dist\project_intel_smoke_test(遠端備份版)\test_plan_ui_origin_copy_1.py", line 734, in main
    self.gotoPath(gitPath)
  File "d:\Tinghao.Chen\Desktop\project_intel_smoke_test\dist\project_intel_smoke_test(遠端備份版)\test_plan_ui_origin_copy_1.py", line 676, in gotoPath
    os.chdir(gitPath)
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。: 'D:/SourceCode_SM2269'
ERROR 2022-07-25 11:20:54,423 - Error Message from Class of getSHA
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\project_intel_smoke_test\dist\project_intel_smoke_test(遠端備份版)\test_plan_ui_origin_copy_1.py", line 734, in main
    self.gotoPath(gitPath)
  File "d:\Tinghao.Chen\Desktop\project_intel_smoke_test\dist\project_intel_smoke_test(遠端備份版)\test_plan_ui_origin_copy_1.py", line 676, in gotoPath
    os.chdir(gitPath)
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。: 'D:/SourceCode_SM2269'
ERROR 2022-07-25 11:20:54,972 - Error Message from Class of getSHA
Traceback (most recent call last):
  File "d:\Tinghao.Chen\Desktop\project_intel_smoke_test\dist\project_intel_smoke_test(遠端備份版)\test_plan_ui_origin_copy_1.py", line 734, in main
    self.gotoPath(gitPath)
  File "d:\Tinghao.Chen\Desktop\project_intel_smoke_test\dist\project_intel_smoke_test(遠端備份版)\test_plan_ui_origin_copy_1.py", line 676, in gotoPath
    os.chdir(gitPath)
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。: 'D:/SourceCode_SM2269'
